project_id = "vxqrvepgtvdraqjavxsz"

[functions.fetch-exchange-rate]
verify_jwt = false

[functions.get-dashboard-data]
verify_jwt = false

[functions.get-savings-data]
verify_jwt = false

[functions.get-transactions-data]
verify_jwt = false

[functions.gmail-oauth]
verify_jwt = false

[functions.gmail-webhook]
verify_jwt = false

[functions.gmail-process-history]
verify_jwt = false

[functions.gmail-sync]
verify_jwt = false
